### ISSUE TITLE
Project Proposal: Move message attributes to device config file

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#93]
**Project Description**

While the Device Config File is a reference library specific config file, it's been great for adding devices without changing code so far. It would be nice to add device names and MessageAttributes to this file, so that we could possible add message attributes as needed.

Possible issues:
- How do we define specific devices here, especially when sometimes the hardware must be queried for its type?
- What would the query chain look like to decide which device is which?

**Comment by qdot** [comment]
Ok, thinking about this more now that the Titan1.1 identifies and works as both a Kiiroo21 and Kiiroo21Vibe device, meaning we need to merge these protocols. It'd be nice if we could handle this in the device config in the future.

I'm thinking we should add another block at the protocol level, so it'd look something like this. I've added comments inline to explain the new attributes.

```yaml
protocols:  
    lovense:
    btle:
      names:
        - LVS-*
      services:
        0000fff0-0000-1000-8000-00805f9b34fb:
          tx: 0000fff2-0000-1000-8000-00805f9b34fb
          rx: 0000fff1-0000-1000-8000-00805f9b34fb
        6e400001-b5a3-f393-e0a9-e50e24dcca9e:
          tx: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
          rx: 6e400003-b5a3-f393-e0a9-e50e24dcca9e
        50300001-0024-4bd4-bbd5-a6920e4c5653:
          tx: 50300002-0024-4bd4-bbd5-a6920e4c5653
          rx: 50300003-0024-4bd4-bbd5-a6920e4c5653
        57300001-0023-4bd4-bbd5-a6920e4c5653:
          tx: 57300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 57300003-0023-4bd4-bbd5-a6920e4c5653
        5a300001-0024-4bd4-bbd5-a6920e4c5653:
          tx: 5a300002-0024-4bd4-bbd5-a6920e4c5653
          rx: 5a300003-0024-4bd4-bbd5-a6920e4c5653
        50300001-0023-4bd4-bbd5-a6920e4c5653:
          tx: 50300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 50300003-0023-4bd4-bbd5-a6920e4c5653
        53300001-0023-4bd4-bbd5-a6920e4c5653:
          tx: 53300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 53300003-0023-4bd4-bbd5-a6920e4c5653
        5a300001-0023-4bd4-bbd5-a6920e4c5653:
          tx: 5a300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 5a300003-0023-4bd4-bbd5-a6920e4c5653
        4f300001-0023-4bd4-bbd5-a6920e4c5653:
          tx: 4f300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 4f300003-0023-4bd4-bbd5-a6920e4c5653
        42300001-0023-4bd4-bbd5-a6920e4c5653: # Max 2
          tx: 42300002-0023-4bd4-bbd5-a6920e4c5653
          rx: 42300003-0023-4bd4-bbd5-a6920e4c5653
    devices:
      # Identifier will be protocol specific. For instance, for the
      # Lovense, this letter will be pulled via the device status
      # query we do on the initialize call.
      - identifier: B
        # This will handle our display name. We could possibly
        # internationalize this if we wanted to get fancy, hence the
        # language specifier.
        name:
          en-us: Lovense Max
        # Here's where we say what messages in the protocol the toy
        # supports. This would let us just define "lovense" or
        # "kiiroo21" and then specify messages here. This would also
        # allow people to integrate their own devices without having
        # to change code, since they could set their own parameters
        # out here.
        messages:
          VibrateCmd:
            FeatureCount: 1
            StepsCount: 20
      - identifier: P
        name: Lovense Edge
        messages:
          VibrateCmd:
            FeatureCount: 2
            StepsCount: 20
  kiiroo21:
    btle:
      names:
        - Onyx2.1
        - Titan1.1
      services:
        00001900-0000-1000-8000-00805f9b34fb:
          # Used to clear the whitelist
          whitelist: 00001901-0000-1000-8000-00805f9b34fb
          tx: 00001902-0000-1000-8000-00805f9b34fb
          rx: 00001903-0000-1000-8000-00805f9b34fb
    # Here's the protocol that kicked off this redesign, the Kiiroo21
    # with Titan and Onyx.
    devices:
      # Here, we use the bluetooth name as the identifier. This will
      # probably be the default.
      - identifier: Titan1.1
        name: Kiiroo Titan 1.1
        messages:
          VibrateCmd:
            FeatureCount: 3
            # InternalFeatureIndexes is only used internally by the
            # protocol, for protocols where everything but the indexes
            # of the features are different.
            InternalFeatureIndexes:
              - 0
              - 1
              - 2
            StepsCount: 100
          FleshlightLaunchFW12Cmd:
            null
          LinearCmd:
            FeatureCount: 1
            StepsCount: 100
      - identifier: Onyx2.1
        name: Kiiroo Onyx 2.1
        messages:
          FleshlightLaunchFW12Cmd:
            null
          LinearCmd:
            FeatureCount: 1
            StepsCount: 100
```
